### ISSUE TITLE
TI API

### ISSUE THREAD

**Issue by dimembermatt** [AeybelV/PartPal#12]
I would like to add TI as a distributor of choice; pricing for TI parts tend to be favorable (by often 20-50%) over aggregators like Mouser and Digikey.

They also have an API for pricing, stats, and cart building: https://api-portal.ti.com/store-api-getstarted

**Comment by AeybelV** [comment]
> I would like to add TI as a distributor of choice; pricing for TI parts tend to be favorable (by often 20-50%) over aggregators like Mouser and Digikey.
> 
> 
> 
> They also have an API for pricing, stats, and cart building: https://api-portal.ti.com/store-api-getstarted

Unable to implement without TI Business account, closing issue for now.
